import type { Metadata } from "next";
import { Unbounded } from "next/font/google"; // Шрифт Unbounded: https://fonts.google.com/specimen/Unbounded
import "./globals.css";

// Инициализация шрифта Unbounded
const unbounded = Unbounded({
    subsets: ["latin"], // Поддержка латиницы и кириллицы
    variable: "--font-unbounded",
    weight: ["400", "500", "600", "700"], // Доступные начертания
});

export const metadata: Metadata = {
    title: "GX+",
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={unbounded.className}>
      <body>{children}</body>
    </html>
  )
}